import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { detectConfigVersion } from '../../src/core/configVersion.js';
import { discover, readDiscoveredFile } from '../../src/core/discovery.js';
import { parseConfigDocument } from '../../src/core/parse/index.js';
import {
  pointerToPath,
  schemaUnavailableReason,
  unsupportedSchemaFormats,
  validateTauriConfig,
} from '../../src/core/schemaValidate.js';

describe('vendored schemas compile', () => {
  it('uses no format this validator does not implement', () => {
    // An unknown format is silently ignored by ajv, so validation gets quietly
    // weaker with nothing failing. Refreshing the vendored schemas can introduce
    // one; this is how we find out. Tauri's schema is generated by schemars and
    // uses Rust type names (uint8, uint32, ...) that ajv-formats does not ship.
    expect(unsupportedSchemaFormats()).toEqual([]);
  });

  it('enforces the registered unsigned integer bounds', () => {
    // Proof the uint formats actually validate rather than merely being present.
    const tooBig = validateTauriConfig(
      { identifier: 'com.demo', app: { trayIcon: { iconAsTemplate: false } }, bundle: { android: { minSdkVersion: 999999999999 } } },
      'v2',
    );
    expect(tooBig.some((issue) => issue.instancePath.includes('minSdkVersion'))).toBe(true);
  });

  // Without this, a schema that fails to compile is indistinguishable from a
  // config with no problems: validation just returns an empty issue list. The
  // v2 schema really does fail to compile under ajv's default settings (its
  // Windows-filename pattern is invalid under the `u` flag), so this assertion
  // is load-bearing, not ceremonial.
  it.each(['v1', 'v2'] as const)('%s', (version) => {
    expect(schemaUnavailableReason(version)).toBeUndefined();
  });
});

const CORPUS_ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'corpus');

describe('pointerToPath', () => {
  it('converts an ajv JSON pointer into a document path', () => {
    expect(pointerToPath('/app/security/csp')).toEqual(['app', 'security', 'csp']);
    expect(pointerToPath('')).toEqual([]);
  });

  it('converts numeric segments into array indices', () => {
    expect(pointerToPath('/app/windows/0/title')).toEqual(['app', 'windows', 0, 'title']);
  });

  it('unescapes the reserved pointer sequences', () => {
    expect(pointerToPath('/a~1b/c~0d')).toEqual(['a/b', 'c~d']);
  });
});

describe('validateTauriConfig', () => {
  it('accepts a minimal valid v2 config', () => {
    expect(
      validateTauriConfig({ productName: 'demo', version: '0.1.0', identifier: 'com.demo' }, 'v2'),
    ).toEqual([]);
  });

  it('reports a type mismatch with a resolvable path', () => {
    const issues = validateTauriConfig(
      { identifier: 'com.demo', app: { withGlobalTauri: 'yes please' } },
      'v2',
    );
    expect(issues.length).toBeGreaterThan(0);
    const issue = issues.find((candidate) => candidate.instancePath === '/app/withGlobalTauri');
    expect(issue).toBeDefined();
    expect(issue?.path).toEqual(['app', 'withGlobalTauri']);
  });

  it('never throws on hostile input', () => {
    for (const value of [null, undefined, 42, 'x', [], { app: { security: [] } }]) {
      expect(() => validateTauriConfig(value, 'v2')).not.toThrow();
      expect(() => validateTauriConfig(value, 'v1')).not.toThrow();
    }
  });

  it('does not flag a templated updater endpoint', () => {
    // The schema says `format: uri` while its own field description tells you to
    // write `{{target}}` placeholders. Tauri's own examples/api config does this.
    const issues = validateTauriConfig(
      {
        build: { distDir: '../dist', devPath: '../dist' },
        package: { productName: 'demo', version: '0.1.0' },
        tauri: {
          updater: {
            active: true,
            endpoints: ['https://updates.example.com/{{target}}/{{current_version}}'],
          },
        },
      },
      'v1',
    );
    expect(issues).toEqual([]);
  });

  it('does not extend the template exemption to other uri fields', () => {
    // `tauri.allowlist.http.scope` is also `format: uri`, but its schema does not
    // document placeholders, so it is outside the allowlist. If this stops being
    // reported, `{{` has become a universal way to bypass format checks.
    const issues = validateTauriConfig(
      {
        build: { distDir: '../dist', devPath: '../dist' },
        package: { productName: 'demo', version: '0.1.0' },
        tauri: { allowlist: { http: { scope: ['not a url {{target}}'] } } },
      },
      'v1',
    );
    expect(issues.some((issue) => issue.instancePath.startsWith('/tauri/allowlist/http/scope'))).toBe(
      true,
    );
  });

  it('still flags a genuinely malformed endpoint', () => {
    // The suppression above must not become a blanket exemption for `format`.
    const issues = validateTauriConfig(
      {
        build: { distDir: '../dist', devPath: '../dist' },
        package: { productName: 'demo', version: '0.1.0' },
        tauri: { updater: { active: true, endpoints: ['definitely not a url'] } },
      },
      'v1',
    );
    expect(issues.length).toBeGreaterThan(0);
  });

  it('validates v1 documents against the v1 schema', () => {
    const v1 = {
      build: { distDir: '../dist', devPath: '../dist' },
      package: { productName: 'demo', version: '0.1.0' },
      tauri: { allowlist: { all: false } },
    };
    expect(validateTauriConfig(v1, 'v1')).toEqual([]);
  });
});

describe('corpus: real configs validate against the vendored schemas', () => {
  // This is the check that matters. The vendored v2 schema tracks one Tauri
  // release (2.11.5) while these apps track several older ones, so this test is
  // really asking: does our pinned schema disagree with configs that are
  // perfectly valid for the release they were written against?
  const apps = [
    { group: 'clean', name: 'surrealist' },
    { group: 'clean', name: 'ecopaste' },
    { group: 'clean', name: 'yaak' },
    { group: 'clean', name: 'tauri-helloworld-v1' },
    { group: 'clean', name: 'tauri-isolation-v1' },
    { group: 'true-positive', name: 'tauri-api-v1' },
  ] as const;

  it.each(apps)('$group/$name', ({ group, name }) => {
    const root = path.join(CORPUS_ROOT, group, name);
    const configs = discover(root).files.filter((file) => file.kind === 'tauri-config');
    expect(configs.length).toBeGreaterThan(0);

    const reported: string[] = [];
    for (const file of configs) {
      const text = readDiscoveredFile(file.path) ?? '';
      const doc = parseConfigDocument(file.path, text);
      const version = detectConfigVersion(doc?.value).version;
      if (version === 'unknown') continue;

      for (const issue of validateTauriConfig(doc?.value, version)) {
        reported.push(`${path.relative(root, file.path)}${issue.instancePath}: ${issue.message}`);
      }
    }

    expect(reported).toEqual([]);
  });
});
